[build]
  command = "npm run build"
  publish = "build/client"

[build.environment]
  NODE_VERSION = "20.11.1"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/remix"
  status = 200

[dev]
  command = "npm run dev"
  framework = "vite" 