[build]
  command = "npm run build"
  publish = "build/client"
  functions = ".netlify/functions-internal"

[build.environment]
  NODE_VERSION = "20.11.1"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/remix"
  status = 200

[dev]
  command = "npm run dev"
  framework = "vite" 