[build]
  command = "npm run build"
  publish = "build/client"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/remix"
  status = 200

[dev]
  command = "npm run dev"
  framework = "vite" 